version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commander
    versions:
    - ">= 6.a, < 7"
  - dependency-name: purgecss
    versions:
    - ">= 3.a, < 4"
  - dependency-name: purgecss
    versions:
    - ">= 4.a, < 5"
  - dependency-name: standard
    versions:
    - ">= 16.a, < 17"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
